### ISSUE TITLE
apk add make no longer working

### ISSUE THREAD

**Issue by Chris-StJohn-Bose** [ThrowTheSwitch/MadScienceLabDocker#7]
I'm trying to track down a problem that making our GIthub Actions fail:
```
Run apk --no-cache add make
/__w/_temp/d29c2ced-5f4f-4033-974c-33fbd3b2209[1](https://github.com/####/actions/runs/12141539964/job/33853871089#step:4:1).sh: 1: apk: not found
Error: Process completed with exit code 127.
```
and I see that there has been a recent release of throwtheswitch/madsciencelab docker image
https://hub.docker.com/layers/throwtheswitch/madsciencelab/latest/images/sha256-e9cf21aa149cbe3036667f538a5d2733455be89e9b820acde198dfef4f69fedf?context=explore

which I'm _guessing_ comes from this branch (since master hasn't changed in over 2 years)
https://github.com/ThrowTheSwitch/MadScienceLabDocker/tree/secure-and-more-better

Downgrade to throwtheswitch/madsciencelab:0.3.2 fixes the issue

As an aside, this project might want to sort out some sort of process for docker image releases? Like a PR or something...

**Comment by mkarlesky** [comment]
Hi, @Chris-StJohn-Bose. So sorry for this trouble.

I'm going to take an educated guess as to what happened. Is your build based on the `madsciencelab:latest` image? If so, then what you pulled in is the 1.0.0-prerelease image containing a huge update to the tools it contains (official release very soon).

One of several important changes in the Docker image itself is a security best practice of creating a non-root user in the image. Otherwise, the default image (such as was built for 0.3.2) has potentially dangerous elevated privileges given how Docker operates. As such, the new `dev` user in the latest image does not have privileges to install software inside the container.

You have two solutions here (if you want to use the newest software—recommended):

1. Run the container with `-u root` (probably fine in a Github Action).
1. Restructure your build to create your own Docker image from MadScienceLab and add to it for your needs.

I don't honestly know what is considered best practice in regard to `:latest` images. I've seen wildly different uses and assumptions. I'd suggest it may be best to pin your build to a specific tag rather than latest. Especially when the software inside an image jumps a whole major version number, unexpected results are inevitable.

As for the release process, we're working on it… After a long while of not receiving enough attention all the tools are getting updates, better documentation, and better processes. The Docker images are presently the runt of the litter apart from some much improved plumbing within so far.

**Comment by Chris-StJohn-Bose** [comment]
Hi @mkarlesky. No need to apologise :-)

I see what you mean about privilege escalation. Perhaps you could consider setting the setuid bit on `apk` since that's probably the most common reason for `sudo` in this environment, or add some scripts to install common tools like make.

As for the use of `:latest` - again I see your point. I tend to pull in the latest so I get early warning that something is breaking. Tagging to 0.3.2 is no problem as long as I remember to remove the tag sometime after 1.0.0 is released so I continue to get improvements.

Thanks for your time and effort supporting this project. Might not seem like it, but these tools are used by a lot of people!

Chris

**Comment by mkarlesky** [comment]
@Chris-StJohn-Bose That's a good idea on configuring to allow installing packages. Thank you for that.

**Comment by mkarlesky** [comment]
@Chris-StJohn-Bose I did a bit of research on the security implications of granting permissions to install packages as a non-root user. All of the approaches I've found are considered insecure enough that it effectively undoes the protections of a Docker image built as a non-root user.

So, I think what we will do is:
1. Install `build-essentials` so `make` is present. It adds a fair amount to already hefty containers, but it's a toolset that probably should be there.
1. Discuss this topic thoroughly in the image documentation (TBD).
1. Add a blurb to the welcome message when running the container as a terminal that explains the security issue and points them to the documentation.
